export default [
    { id: 1, type: 'solar', title: 'عید نوروز', holiday: true },
    { id: 2, type: 'solar', title: 'عید نوروز', holiday: true },
    { id: 3, type: 'solar', title: 'عید نوروز', holiday: true },
    { id: 4, type: 'solar', title: 'عید نوروز', holiday: true },
    { id: 12, type: 'solar', title: 'روز جمهوری اسلامی', holiday: true },
    { id: 13, type: 'solar', title: 'روز طبیعت', holiday: true },
    { id: 76, type: 'solar', title: 'رحلت امام خمینی', holiday: true },
    { id: 77, type: 'solar', title: 'قیام خونین ۱۵ خرداد', holiday: true },
    { id: 100, type: 'solar', title: 'شهادت دکتر بهشتی', holiday: false },
    { id: 132, type: 'solar', title: 'روز مبارزه با تروریسم', holiday: false },
    { id: 135, type: 'solar', title: 'روز صنعت چاپ', holiday: false },
    { id: 276, type: 'solar', title: 'شب یلدا', holiday: false },
    { id: 328, type: 'solar', title: 'پیروزی انقلاب اسلامی', holiday: true },
    { id: 365, type: 'solar', title: 'روز ملی شدن صنعت نفت', holiday: true },
];
